# .github/workflows/sample.yml

name: workflow-name

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:

    - name: sample run
      run: echo "何でもできる"

    - name: sample uses
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go